[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:uvicorn]
command=uvicorn main:app --host 0.0.0.0 --port %(ENV_PORT)s
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery_worker]
command=celery -A app.celery_app:celery_app worker --loglevel=info --concurrency=2
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery_beat]
command=celery -A app.celery_app:celery_app beat --loglevel=info --schedule /tmp/celerybeat-schedule
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
