"""Static structured-output table: program profile per FBS team.

One row per ``cfbd_teams`` row, generated by the LLM via the
``ProgramProfileDefinition`` static definition. Mirrors the
``ProgramProfileOutput`` Pydantic model field-for-field — the two must stay in
sync (adding/removing/renaming a category means updating both here and in
``app/services/struct_output/definitions/program_profile.py``, plus a migration).

Unlike the dynamic tier's ``CREATE TABLE IF NOT EXISTS`` tables, this table is a
real Alembic-migrated ORM model — so its schema evolves through migrations (no
silent drift) and it is queryable via the ORM.
"""

from datetime import datetime

from sqlalchemy import ForeignKey, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class StructOutputProgramProfile(Base):
    """LLM-generated program-profile ranking for one FBS team.

    PK ``cfbd_team_id`` is the FK to ``cfbd_teams.id`` — one row per source entity
    (the convention every static output table follows, so the runner can upsert by
    entity id).
    """

    __tablename__ = "struct_output_program_profile"

    cfbd_team_id: Mapped[int] = mapped_column(
        ForeignKey("cfbd_teams.id"), primary_key=True
    )

    # --- 10 profile categories: score (1-10) / tier / rationale each -----------
    historical_prestige_score: Mapped[int] = mapped_column(Integer, nullable=False)
    historical_prestige_tier: Mapped[str] = mapped_column(String, nullable=False)
    historical_prestige_rationale: Mapped[str] = mapped_column(String, nullable=False)

    stadium_atmosphere_score: Mapped[int] = mapped_column(Integer, nullable=False)
    stadium_atmosphere_tier: Mapped[str] = mapped_column(String, nullable=False)
    stadium_atmosphere_rationale: Mapped[str] = mapped_column(String, nullable=False)

    fanbase_passion_score: Mapped[int] = mapped_column(Integer, nullable=False)
    fanbase_passion_tier: Mapped[str] = mapped_column(String, nullable=False)
    fanbase_passion_rationale: Mapped[str] = mapped_column(String, nullable=False)

    brand_marketability_score: Mapped[int] = mapped_column(Integer, nullable=False)
    brand_marketability_tier: Mapped[str] = mapped_column(String, nullable=False)
    brand_marketability_rationale: Mapped[str] = mapped_column(String, nullable=False)

    facilities_resources_score: Mapped[int] = mapped_column(Integer, nullable=False)
    facilities_resources_tier: Mapped[str] = mapped_column(String, nullable=False)
    facilities_resources_rationale: Mapped[str] = mapped_column(String, nullable=False)

    nfl_pipeline_score: Mapped[int] = mapped_column(Integer, nullable=False)
    nfl_pipeline_tier: Mapped[str] = mapped_column(String, nullable=False)
    nfl_pipeline_rationale: Mapped[str] = mapped_column(String, nullable=False)

    recruiting_nil_score: Mapped[int] = mapped_column(Integer, nullable=False)
    recruiting_nil_tier: Mapped[str] = mapped_column(String, nullable=False)
    recruiting_nil_rationale: Mapped[str] = mapped_column(String, nullable=False)

    academic_profile_score: Mapped[int] = mapped_column(Integer, nullable=False)
    academic_profile_tier: Mapped[str] = mapped_column(String, nullable=False)
    academic_profile_rationale: Mapped[str] = mapped_column(String, nullable=False)

    conference_strength_score: Mapped[int] = mapped_column(Integer, nullable=False)
    conference_strength_tier: Mapped[str] = mapped_column(String, nullable=False)
    conference_strength_rationale: Mapped[str] = mapped_column(String, nullable=False)

    rivalries_culture_score: Mapped[int] = mapped_column(Integer, nullable=False)
    rivalries_culture_tier: Mapped[str] = mapped_column(String, nullable=False)
    rivalries_culture_rationale: Mapped[str] = mapped_column(String, nullable=False)

    # --- overall ------------------------------------------------------------
    overall_score: Mapped[int] = mapped_column(Integer, nullable=False)
    overall_rationale: Mapped[str] = mapped_column(String, nullable=False)

    # --- bookkeeping ---------------------------------------------------------
    generated_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=func.now()
    )
    model: Mapped[str | None] = mapped_column(String, nullable=True)
    run_id: Mapped[str | None] = mapped_column(String, nullable=True)
